using System.ComponentModel;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace Coh3Trainer.Localization;

public interface ITextLocalizer
{
    string CultureName { get; }
    string Get(string key, params object[] arguments);
}

public sealed record LanguageOption(string CultureName, string DisplayName);

public sealed class LocalizationService : ITextLocalizer, INotifyPropertyChanged
{
    private const string FallbackCulture = "pt-BR";
    private readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> _catalogs;
    private string _cultureName = FallbackCulture;

    private LocalizationService()
    {
        _catalogs = CreateCatalogs();
        ValidateCatalogs(_catalogs);
    }

    public static LocalizationService Current { get; } = new();

    public static IReadOnlyList<LanguageOption> SupportedLanguages { get; } =
    [
        new("pt-BR", "Português (Brasil)"),
        new("en-US", "English"),
        new("zh-CN", "中文（简体）"),
        new("es-ES", "Español")
    ];

    public string CultureName => _cultureName;

    public string this[string key] => Get(key);

    public event PropertyChangedEventHandler? PropertyChanged;
    public event EventHandler? CultureChanged;

    public bool SetCulture(string? cultureName)
    {
        var normalized = NormalizeCultureName(cultureName);
        if (string.Equals(_cultureName, normalized, StringComparison.OrdinalIgnoreCase))
        {
            ApplyThreadCulture(normalized);
            return false;
        }

        _cultureName = normalized;
        ApplyThreadCulture(normalized);
        OnPropertyChanged("Item[]");
        CultureChanged?.Invoke(this, EventArgs.Empty);
        return true;
    }

    public string Get(string key, params object[] arguments)
    {
        if (!_catalogs[_cultureName].TryGetValue(key, out var template) &&
            !_catalogs[FallbackCulture].TryGetValue(key, out template))
        {
            return $"[{key}]";
        }

        return arguments.Length == 0
            ? template
            : string.Format(CultureInfo.CurrentCulture, template, arguments);
    }

    public static bool IsSupportedCulture(string? cultureName) =>
        SupportedLanguages.Any(language =>
            string.Equals(language.CultureName, cultureName, StringComparison.OrdinalIgnoreCase));

    public static string NormalizeCultureName(string? cultureName) =>
        SupportedLanguages.FirstOrDefault(language =>
            string.Equals(language.CultureName, cultureName, StringComparison.OrdinalIgnoreCase))
            ?.CultureName ?? FallbackCulture;

    public IReadOnlyCollection<string> GetMissingKeys(string cultureName)
    {
        var normalized = NormalizeCultureName(cultureName);
        return _catalogs[FallbackCulture].Keys
            .Except(_catalogs[normalized].Keys, StringComparer.Ordinal)
            .ToArray();
    }

    private static void ApplyThreadCulture(string cultureName)
    {
        var culture = CultureInfo.GetCultureInfo(cultureName);
        CultureInfo.DefaultThreadCurrentCulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
    }

    private static void ValidateCatalogs(
        IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> catalogs)
    {
        var referenceKeys = catalogs[FallbackCulture].Keys.ToHashSet(StringComparer.Ordinal);
        foreach (var (culture, catalog) in catalogs)
        {
            var missing = referenceKeys.Except(catalog.Keys, StringComparer.Ordinal).ToArray();
            if (missing.Length > 0)
            {
                throw new InvalidOperationException(
                    $"The {culture} localization catalog is missing: {string.Join(", ", missing)}");
            }
        }
    }

    private void OnPropertyChanged([CallerMemberName] string? propertyName = null) =>
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

    private static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> CreateCatalogs() =>
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["pt-BR"] = CreatePortugueseCatalog(),
            ["en-US"] = CreateEnglishCatalog(),
            ["zh-CN"] = CreateChineseCatalog(),
            ["es-ES"] = CreateSpanishCatalog()
        };

    private static Dictionary<string, string> CreatePortugueseCatalog() => new(StringComparer.Ordinal)
    {
        ["App.Title"] = "CoH3 Resource Trainer",
        ["App.AlreadyRunningTitle"] = "Trainer já está em execução",
        ["App.AlreadyRunning"] = "Feche a instância atual do CoH3 Resource Trainer antes de abrir outra.",
        ["Menu.Main"] = "Menu principal",
        ["Menu.Settings"] = "_CONFIGURAÇÕES",
        ["Menu.Language"] = "Idioma",
        ["Menu.OpenSettingsFolder"] = "Abrir pasta de configurações",
        ["Menu.OpenLogsFolder"] = "Abrir pasta de logs",
        ["Menu.Help"] = "_AJUDA",
        ["Menu.HowTo"] = "Como usar",
        ["Menu.Contributors"] = "Colaboradores",
        ["Menu.About"] = "Sobre",
        ["Header.Subtitle"] = "Campanha e partidas solo/privadas contra IA",
        ["Action.Connect"] = "CONECTAR",
        ["Action.Disconnect"] = "DESCONECTAR",
        ["Action.Retry"] = "TENTAR NOVAMENTE",
        ["Action.Connecting"] = "CONECTANDO...",
        ["Action.Add"] = "ADICIONAR",
        ["Action.Promote"] = "PROMOVER TODOS +1",
        ["Action.Heal"] = "CURAR TODOS",
        ["Action.ResetCooldowns"] = "ZERAR TODOS",
        ["Action.SaveSettings"] = "SALVAR CONFIGURAÇÃO",
        ["Action.Close"] = "FECHAR",
        ["Status.Initializing"] = "Inicializando...",
        ["Status.WaitingData"] = "Aguardando dados",
        ["Status.Updated"] = "Atualizado {0:HH:mm:ss.fff}",
        ["Status.WaitingConnection"] = "Aguardando conexão.",
        ["Tab.Trainer"] = "TRAINER",
        ["Tab.Units"] = "UNIDADES",
        ["Tab.Match"] = "PARTIDA",
        ["Tab.Settings"] = "CONFIGURAÇÃO",
        ["Trainer.LiveDataTitle"] = "DADOS DO JOGADOR LOCAL • TEMPO REAL",
        ["Trainer.Instruction"] = "Pressione a tecla configurada ou use o botão. Os valores são somados, não substituídos.",
        ["Units.Title"] = "Veterania, cura e cooldowns",
        ["Units.Subtitle"] = "Aplique a ação a todos os esquadrões do jogador local na partida.",
        ["Units.ConnectHint"] = "Conecte o Trainer ao jogo para habilitar estas ações.",
        ["Units.Unsupported"] = "Ações indisponíveis na versão {0}.",
        ["Units.WaitingMatch"] = "Jogo conectado; aguardando uma partida e o jogador local.",
        ["Units.Executing"] = "Aplicando ação no ciclo de simulação...",
        ["Units.Ready"] = "PRONTO • ações para todos os seus esquadrões",
        ["Units.VeterancyTitle"] = "VETERANIA",
        ["Units.VeterancyDescription"] = "Promove todos os seus esquadrões em uma patente, respeitando o nível máximo de cada unidade.",
        ["Units.HealTitle"] = "CURA",
        ["Units.HealDescription"] = "Restaura para 100% a vida dos integrantes de todos os seus esquadrões.",
        ["Units.CooldownsTitle"] = "COOLDOWNS",
        ["Units.CooldownsDescription"] = "Remove o tempo de recarga restante das habilidades de todos os seus esquadrões.",
        ["Income.DefaultShort"] = "RENDA PADRÃO",
        ["Income.MultiplierShort"] = "RENDA {0:0.#}x",
        ["Population.ShortActive"] = "POP {0:N0}",
        ["Population.ShortDefault"] = "POP PADRÃO",
        ["Population.ShortUnavailable"] = "POP INDISPONÍVEL",
        ["Population.ShortWaiting"] = "POP {0:N0} • AGUARDANDO",
        ["Dashboard.Title"] = "Painel da partida",
        ["Dashboard.Subtitle"] = "Leitura em tempo real do jogador local.",
        ["Dashboard.ObservedTime"] = "TEMPO OBSERVADO",
        ["Dashboard.WaitingConnection"] = "Aguardando conexão com o jogo",
        ["Dashboard.LastSampleEmpty"] = "Última amostra: —",
        ["Dashboard.LastSample"] = "Última amostra: {0:HH:mm:ss}",
        ["Dashboard.VersionEmpty"] = "VERSÃO —",
        ["Dashboard.Version"] = "VERSÃO {0}",
        ["Dashboard.NetChange"] = "Variação líquida: {0}/min",
        ["Dashboard.Income"] = "RENDA",
        ["Dashboard.Population"] = "POPULAÇÃO",
        ["Dashboard.Footnote"] = "A variação líquida considera ganhos, gastos e ações do trainer na janela dos últimos 60 segundos.",
        ["Dashboard.StateDisconnected"] = "DESCONECTADO",
        ["Dashboard.StateInMatch"] = "EM PARTIDA",
        ["Dashboard.StateSyncing"] = "SINCRONIZANDO",
        ["Dashboard.StateWaitingMatch"] = "AGUARDANDO PARTIDA",
        ["Dashboard.TelemetryActive"] = "Telemetria do jogador local ativa",
        ["Dashboard.TelemetryInterrupted"] = "A leitura da partida foi temporariamente interrompida",
        ["Dashboard.EnterMatch"] = "Jogo conectado; entre em uma partida compatível",
        ["Dashboard.IncomeDefault"] = "PADRÃO • 1x",
        ["Dashboard.IncomeActive"] = "ATIVO • {0:0.#}x",
        ["Dashboard.PopActive"] = "ATIVO • {0:N0}",
        ["Dashboard.PopDefault"] = "PADRÃO DO JOGO",
        ["Dashboard.PopUnsupported"] = "INDISPONÍVEL NESTA VERSÃO",
        ["Dashboard.PopWaiting"] = "AGUARDANDO • {0:N0}",
        ["Settings.Title"] = "Atalhos e quantidades",
        ["Settings.HotkeyHint"] = "Cada atalho global aceita uma tecla entre F1 e F12.",
        ["Settings.IncomeMultiplier"] = "Multiplicador de renda",
        ["Settings.IncomeDescription"] = "Multiplica os ganhos observados de Manpower, Fuel e Munições.",
        ["Settings.PopulationLimit"] = "Limite de população",
        ["Settings.PopulationDescription"] = "Substitui o teto de população do jogador local durante a partida.",
        ["Settings.Active"] = "ATIVO",
        ["Settings.PersistHint"] = "As alterações são aplicadas imediatamente e permanecem salvas para as próximas sessões.",
        ["Resource.Manpower"] = "MANPOWER",
        ["Resource.Fuel"] = "FUEL",
        ["Resource.Army"] = "MUNIÇÕES",
        ["Resource.CommandPoints"] = "COMMAND POINTS",
        ["Resource.VictoryPoints"] = "VICTORY POINTS DO TIME",
        ["Automation.CommandPointsAmount"] = "Quantidade de Command Points",
        ["Automation.PopulationLimit"] = "Limite de população",
        ["Tooltip.Connect"] = "Localizar o Company of Heroes 3",
        ["Tooltip.Disconnect"] = "Encerrar a conexão com o processo do jogo",
        ["Tooltip.Connecting"] = "Conexão em andamento",
        ["Event.LanguageChanged"] = "Idioma alterado para {0}.",
        ["Event.SettingsFolderOpened"] = "Pasta de configurações aberta.",
        ["Event.LogsFolderOpened"] = "Pasta de logs aberta.",
        ["Event.CannotOpenFolder"] = "Não foi possível abrir a pasta: {0}",
        ["Event.SettingsSaved"] = "Configuração salva. {0} {1}",
        ["Event.ErrorSaving"] = "Erro ao salvar: {0}",
        ["Event.GameDisconnected"] = "Jogo desconectado.",
        ["Event.Connecting"] = "Conectando ao jogo...",
        ["Event.ConnectionFailed"] = "Falha ao conectar: {0}",
        ["Event.ReadFailed"] = "Falha de leitura: {0}",
        ["Event.UnitActionQueued"] = "Ação enviada ao ciclo de simulação...",
        ["Log.Started"] = "Trainer iniciado.",
        ["Log.Closed"] = "Trainer encerrado.",
        ["Info.HelpSection"] = "AJUDA",
        ["Info.HelpHeading"] = "Como usar",
        ["Info.HelpBody"] = "1. Abra o Company of Heroes 3.\n2. Aguarde a conexão automática ou use Tentar novamente.\n3. Entre em uma partida compatível.\n4. Use os botões ou os atalhos configurados para adicionar recursos.\n5. Command Points usam F9 e adicionam 5 pontos por padrão.\n6. Ajuste o multiplicador de renda e o limite de população na guia Configuração.\n7. Use a guia Unidades para aplicar veterania, cura ou cooldowns a todos os seus esquadrões.",
        ["Info.ContributorsSection"] = "COLABORADORES",
        ["Info.ContributorsBody"] = "Idealizador do CoH3 Resource Trainer e responsável pela visão do projeto.",
        ["Info.AboutSection"] = "SOBRE",
        ["Info.AboutBody"] = "Versão {0}\n\nFerramenta local para campanha e partidas solo ou privadas contra IA.",
        ["Validation.SelectIncome"] = "Selecione um multiplicador de renda válido.",
        ["Validation.IncompleteSettings"] = "A configuração de recursos está incompleta.",
        ["Validation.PopulationRange"] = "O limite de população deve estar entre {0} e {1}.",
        ["Validation.ValidAmount"] = "Informe uma quantidade válida para {0}.",
        ["Validation.CommandPointsRange"] = "A quantidade de Command Points deve estar entre {0} e {1}.",
        ["Validation.ResourceRange"] = "A quantidade de {0} deve estar entre 1 e 1.000.000.",
        ["Validation.DistinctKeys"] = "Selecione {0} teclas F diferentes.",
        ["Hotkey.WindowUnavailable"] = "Janela ainda não inicializada.",
        ["Hotkey.Invalid"] = "Tecla inválida para {0}: {1}",
        ["Hotkey.InUse"] = "{0} já está em uso por outro programa.",
        ["Backend.Disconnected"] = "Jogo não conectado.",
        ["Backend.Locating"] = "Localizando o Company of Heroes 3...",
        ["Backend.NotFound"] = "Company of Heroes 3 não encontrado. Abra o jogo e tente novamente.",
        ["Backend.MainModuleUnavailable"] = "O módulo principal do jogo não está disponível.",
        ["Backend.UnknownVersion"] = "desconhecida",
        ["Backend.Ready"] = "Pronto — recursos disponíveis.",
        ["Backend.ConnectedWaiting"] = "Jogo conectado — aguardando uma partida.",
        ["Backend.ConnectionFailed"] = "Falha na conexão: {0}",
        ["Backend.ResourceNotIdentified"] = "{0} ainda não foi identificado. Entre em uma partida e tente novamente.",
        ["Backend.UnsafeRead"] = "Leitura fora da faixa segura; escrita cancelada.",
        ["Backend.WriteFailed"] = "Falha ao escrever: {0}",
        ["Backend.NotConfirmed"] = "O jogo não confirmou o novo valor.",
        ["Backend.AtLimit"] = "{0} já está no limite de {1:N0}.",
        ["Backend.Added"] = "+{0:N0} em {1}; novo valor: {2:N0}.",
        ["Backend.IncomeRestored"] = "Renda normal restaurada.",
        ["Backend.IncomeActivated"] = "Multiplicador de renda {0:0.#}x ativado.",
        ["Backend.PopDefault"] = "Limite de população padrão selecionado.",
        ["Backend.PopUnsupported"] = "Limite salvo, mas ainda não compatível com a versão {0}.",
        ["Backend.PopConfigured"] = "Limite de população configurado em {0:N0}.",
        ["Backend.UnitActionsUnsupported"] = "Veterania, cura e cooldowns ainda não são compatíveis com a versão {0}.",
        ["Backend.UnitActionTimedOut"] = "A partida não processou a ação. Confirme que está em uma partida e tente novamente.",
        ["Backend.NoSquadsAvailable"] = "Nenhum esquadrão do jogador local está disponível na partida.",
        ["Backend.VeterancyApplied"] = "Veterania aumentada em {0:N0} esquadrão(ões).",
        ["Backend.HealApplied"] = "Vida restaurada em {0:N0} esquadrão(ões).",
        ["Backend.CooldownsApplied"] = "Cooldowns zerados em {0:N0} esquadrão(ões).",
        ["Backend.GameClosed"] = "O jogo foi fechado. Conecte novamente quando estiver pronto.",
        ["Backend.ModuleNotFound"] = "Módulo {0} não encontrado.",
        ["Backend.PointerInvalid"] = "Cadeia de ponteiros inválida para {0}.",
        ["Backend.InitialValueInvalid"] = "Valor inicial inválido para {0}.",
        ["Signature.AlreadyActive"] = "O identificador automático já está ativo.",
        ["Signature.UnitActionInstructionsChanged"] = "O despachante de ações contém uma alteração desconhecida.",
        ["Signature.PlayerInstructionsChanged"] = "As instruções do jogador contêm uma alteração desconhecida.",
        ["Signature.CaptureAllocationFailed"] = "Falha ao reservar a área de captura.",
        ["Signature.QueueInstructionsChanged"] = "As instruções da fila contêm uma alteração desconhecida.",
        ["Signature.Recovered"] = "Identificação automática recuperada de uma conexão anterior.",
        ["Signature.Installed"] = "Identificação automática instalada; aguardando o jogador local.",
        ["Signature.ActivationFailed"] = "Falha ao ativar a identificação automática: {0}",
        ["Signature.PlayerDescription"] = "do jogador",
        ["Signature.QueueDescription"] = "da fila de produção",
        ["Signature.NotFound"] = "A assinatura automática {0} não foi encontrada nesta versão.",
        ["Signature.NotUnique"] = "A assinatura automática {0} não é única.",
        ["Signature.CodePageFailed"] = "Falha ao liberar a página de código.",
        ["Signature.InstructionCacheFailed"] = "Falha ao atualizar o cache de instruções.",
        ["Signature.NoThreads"] = "Nenhuma thread do jogo pôde ser suspensa com segurança.",
        ["Signature.ReadFailed"] = "Falha ao ler 0x{0:X}.",
        ["Signature.WriteFailed"] = "Falha ao escrever 0x{0:X}."
    };

    private static Dictionary<string, string> CreateEnglishCatalog() => new(StringComparer.Ordinal)
    {
        ["App.Title"] = "CoH3 Resource Trainer",
        ["App.AlreadyRunningTitle"] = "Trainer is already running",
        ["App.AlreadyRunning"] = "Close the current CoH3 Resource Trainer instance before opening another.",
        ["Menu.Main"] = "Main menu",
        ["Menu.Settings"] = "_SETTINGS",
        ["Menu.Language"] = "Language",
        ["Menu.OpenSettingsFolder"] = "Open settings folder",
        ["Menu.OpenLogsFolder"] = "Open logs folder",
        ["Menu.Help"] = "_HELP",
        ["Menu.HowTo"] = "How to use",
        ["Menu.Contributors"] = "Contributors",
        ["Menu.About"] = "About",
        ["Header.Subtitle"] = "Campaign and solo/private matches against AI",
        ["Action.Connect"] = "CONNECT",
        ["Action.Disconnect"] = "DISCONNECT",
        ["Action.Retry"] = "TRY AGAIN",
        ["Action.Connecting"] = "CONNECTING...",
        ["Action.Add"] = "ADD",
        ["Action.Promote"] = "PROMOTE ALL +1",
        ["Action.Heal"] = "HEAL ALL",
        ["Action.ResetCooldowns"] = "RESET ALL",
        ["Action.SaveSettings"] = "SAVE SETTINGS",
        ["Action.Close"] = "CLOSE",
        ["Status.Initializing"] = "Initializing...",
        ["Status.WaitingData"] = "Waiting for data",
        ["Status.Updated"] = "Updated {0:HH:mm:ss.fff}",
        ["Status.WaitingConnection"] = "Waiting for connection.",
        ["Tab.Trainer"] = "TRAINER",
        ["Tab.Units"] = "UNITS",
        ["Tab.Match"] = "MATCH",
        ["Tab.Settings"] = "SETTINGS",
        ["Trainer.LiveDataTitle"] = "LOCAL PLAYER DATA • REAL TIME",
        ["Trainer.Instruction"] = "Press the configured key or use the button. Values are added, not replaced.",
        ["Units.Title"] = "Veterancy, healing and cooldowns",
        ["Units.Subtitle"] = "Apply an action to every squad owned by the local player in the match.",
        ["Units.ConnectHint"] = "Connect the Trainer to the game to enable these actions.",
        ["Units.Unsupported"] = "Actions are unavailable for version {0}.",
        ["Units.WaitingMatch"] = "Game connected; waiting for a match and the local player.",
        ["Units.Executing"] = "Applying action in the simulation cycle...",
        ["Units.Ready"] = "READY • actions affect all your squads",
        ["Units.VeterancyTitle"] = "VETERANCY",
        ["Units.VeterancyDescription"] = "Promotes all your squads by one rank, respecting each unit's maximum rank.",
        ["Units.HealTitle"] = "HEALING",
        ["Units.HealDescription"] = "Restores every member of all your squads to 100% health.",
        ["Units.CooldownsTitle"] = "COOLDOWNS",
        ["Units.CooldownsDescription"] = "Removes the remaining ability cooldown time for all your squads.",
        ["Income.DefaultShort"] = "DEFAULT INCOME",
        ["Income.MultiplierShort"] = "INCOME {0:0.#}x",
        ["Population.ShortActive"] = "POP {0:N0}",
        ["Population.ShortDefault"] = "DEFAULT POP",
        ["Population.ShortUnavailable"] = "POP UNAVAILABLE",
        ["Population.ShortWaiting"] = "POP {0:N0} • WAITING",
        ["Dashboard.Title"] = "Match dashboard",
        ["Dashboard.Subtitle"] = "Real-time local player data.",
        ["Dashboard.ObservedTime"] = "OBSERVED TIME",
        ["Dashboard.WaitingConnection"] = "Waiting for game connection",
        ["Dashboard.LastSampleEmpty"] = "Last sample: —",
        ["Dashboard.LastSample"] = "Last sample: {0:HH:mm:ss}",
        ["Dashboard.VersionEmpty"] = "VERSION —",
        ["Dashboard.Version"] = "VERSION {0}",
        ["Dashboard.NetChange"] = "Net change: {0}/min",
        ["Dashboard.Income"] = "INCOME",
        ["Dashboard.Population"] = "POPULATION",
        ["Dashboard.Footnote"] = "Net change includes income, spending, and trainer actions over the last 60 seconds.",
        ["Dashboard.StateDisconnected"] = "DISCONNECTED",
        ["Dashboard.StateInMatch"] = "IN MATCH",
        ["Dashboard.StateSyncing"] = "SYNCING",
        ["Dashboard.StateWaitingMatch"] = "WAITING FOR MATCH",
        ["Dashboard.TelemetryActive"] = "Local player telemetry is active",
        ["Dashboard.TelemetryInterrupted"] = "Match data was temporarily interrupted",
        ["Dashboard.EnterMatch"] = "Game connected; enter a compatible match",
        ["Dashboard.IncomeDefault"] = "DEFAULT • 1x",
        ["Dashboard.IncomeActive"] = "ACTIVE • {0:0.#}x",
        ["Dashboard.PopActive"] = "ACTIVE • {0:N0}",
        ["Dashboard.PopDefault"] = "GAME DEFAULT",
        ["Dashboard.PopUnsupported"] = "UNAVAILABLE IN THIS VERSION",
        ["Dashboard.PopWaiting"] = "WAITING • {0:N0}",
        ["Settings.Title"] = "Hotkeys and amounts",
        ["Settings.HotkeyHint"] = "Each global hotkey accepts one key from F1 to F12.",
        ["Settings.IncomeMultiplier"] = "Income multiplier",
        ["Settings.IncomeDescription"] = "Multiplies observed Manpower, Fuel, and Munitions income.",
        ["Settings.PopulationLimit"] = "Population cap",
        ["Settings.PopulationDescription"] = "Overrides the local player's population cap during the match.",
        ["Settings.Active"] = "ACTIVE",
        ["Settings.PersistHint"] = "Changes are applied immediately and saved for future sessions.",
        ["Resource.Manpower"] = "MANPOWER",
        ["Resource.Fuel"] = "FUEL",
        ["Resource.Army"] = "MUNITIONS",
        ["Resource.CommandPoints"] = "COMMAND POINTS",
        ["Resource.VictoryPoints"] = "TEAM VICTORY POINTS",
        ["Automation.CommandPointsAmount"] = "Command Points amount",
        ["Automation.PopulationLimit"] = "Population cap",
        ["Tooltip.Connect"] = "Locate Company of Heroes 3",
        ["Tooltip.Disconnect"] = "Disconnect from the game process",
        ["Tooltip.Connecting"] = "Connection in progress",
        ["Event.LanguageChanged"] = "Language changed to {0}.",
        ["Event.SettingsFolderOpened"] = "Settings folder opened.",
        ["Event.LogsFolderOpened"] = "Logs folder opened.",
        ["Event.CannotOpenFolder"] = "Could not open the folder: {0}",
        ["Event.SettingsSaved"] = "Settings saved. {0} {1}",
        ["Event.ErrorSaving"] = "Error while saving: {0}",
        ["Event.GameDisconnected"] = "Game disconnected.",
        ["Event.Connecting"] = "Connecting to the game...",
        ["Event.ConnectionFailed"] = "Connection failed: {0}",
        ["Event.ReadFailed"] = "Read failed: {0}",
        ["Event.UnitActionQueued"] = "Action sent to the simulation cycle...",
        ["Log.Started"] = "Trainer started.",
        ["Log.Closed"] = "Trainer closed.",
        ["Info.HelpSection"] = "HELP",
        ["Info.HelpHeading"] = "How to use",
        ["Info.HelpBody"] = "1. Open Company of Heroes 3.\n2. Wait for automatic connection or use Try again.\n3. Enter a compatible match.\n4. Use the buttons or configured hotkeys to add resources.\n5. Command Points use F9 and add 5 points by default.\n6. Adjust the income multiplier and population cap in the Settings tab.\n7. Use the Units tab to apply veterancy, healing, or cooldown resets to all your squads.",
        ["Info.ContributorsSection"] = "CONTRIBUTORS",
        ["Info.ContributorsBody"] = "Creator of CoH3 Resource Trainer and responsible for the project's vision.",
        ["Info.AboutSection"] = "ABOUT",
        ["Info.AboutBody"] = "Version {0}\n\nLocal tool for campaign and solo or private matches against AI.",
        ["Validation.SelectIncome"] = "Select a valid income multiplier.",
        ["Validation.IncompleteSettings"] = "The resource configuration is incomplete.",
        ["Validation.PopulationRange"] = "The population cap must be between {0} and {1}.",
        ["Validation.ValidAmount"] = "Enter a valid amount for {0}.",
        ["Validation.CommandPointsRange"] = "The Command Points amount must be between {0} and {1}.",
        ["Validation.ResourceRange"] = "The {0} amount must be between 1 and 1,000,000.",
        ["Validation.DistinctKeys"] = "Select {0} different F keys.",
        ["Hotkey.WindowUnavailable"] = "The window has not been initialized yet.",
        ["Hotkey.Invalid"] = "Invalid key for {0}: {1}",
        ["Hotkey.InUse"] = "{0} is already in use by another program.",
        ["Backend.Disconnected"] = "Game not connected.",
        ["Backend.Locating"] = "Locating Company of Heroes 3...",
        ["Backend.NotFound"] = "Company of Heroes 3 was not found. Open the game and try again.",
        ["Backend.MainModuleUnavailable"] = "The game's main module is unavailable.",
        ["Backend.UnknownVersion"] = "unknown",
        ["Backend.Ready"] = "Ready — resources available.",
        ["Backend.ConnectedWaiting"] = "Game connected — waiting for a match.",
        ["Backend.ConnectionFailed"] = "Connection failed: {0}",
        ["Backend.ResourceNotIdentified"] = "{0} has not been identified yet. Enter a match and try again.",
        ["Backend.UnsafeRead"] = "Value outside the safe range; write canceled.",
        ["Backend.WriteFailed"] = "Write failed: {0}",
        ["Backend.NotConfirmed"] = "The game did not confirm the new value.",
        ["Backend.AtLimit"] = "{0} is already at the {1:N0} limit.",
        ["Backend.Added"] = "+{0:N0} to {1}; new value: {2:N0}.",
        ["Backend.IncomeRestored"] = "Normal income restored.",
        ["Backend.IncomeActivated"] = "{0:0.#}x income multiplier enabled.",
        ["Backend.PopDefault"] = "Default population cap selected.",
        ["Backend.PopUnsupported"] = "Cap saved, but not yet compatible with version {0}.",
        ["Backend.PopConfigured"] = "Population cap set to {0:N0}.",
        ["Backend.UnitActionsUnsupported"] = "Veterancy, healing and cooldowns are not yet compatible with version {0}.",
        ["Backend.UnitActionTimedOut"] = "The match did not process the action. Confirm that a match is running and try again.",
        ["Backend.NoSquadsAvailable"] = "No local-player squad is available in the match.",
        ["Backend.VeterancyApplied"] = "Veterancy increased for {0:N0} squad(s).",
        ["Backend.HealApplied"] = "Health restored for {0:N0} squad(s).",
        ["Backend.CooldownsApplied"] = "Cooldowns reset for {0:N0} squad(s).",
        ["Backend.GameClosed"] = "The game was closed. Connect again when ready.",
        ["Backend.ModuleNotFound"] = "Module {0} was not found.",
        ["Backend.PointerInvalid"] = "Invalid pointer chain for {0}.",
        ["Backend.InitialValueInvalid"] = "Invalid initial value for {0}.",
        ["Signature.AlreadyActive"] = "The automatic locator is already active.",
        ["Signature.UnitActionInstructionsChanged"] = "The unit-action dispatcher contains an unknown change.",
        ["Signature.PlayerInstructionsChanged"] = "The player instructions contain an unknown change.",
        ["Signature.CaptureAllocationFailed"] = "Failed to allocate the capture area.",
        ["Signature.QueueInstructionsChanged"] = "The production queue instructions contain an unknown change.",
        ["Signature.Recovered"] = "Automatic identification recovered from a previous connection.",
        ["Signature.Installed"] = "Automatic identification installed; waiting for the local player.",
        ["Signature.ActivationFailed"] = "Failed to enable automatic identification: {0}",
        ["Signature.PlayerDescription"] = "for the player",
        ["Signature.QueueDescription"] = "for the production queue",
        ["Signature.NotFound"] = "The automatic signature {0} was not found in this version.",
        ["Signature.NotUnique"] = "The automatic signature {0} is not unique.",
        ["Signature.CodePageFailed"] = "Failed to unlock the code page.",
        ["Signature.InstructionCacheFailed"] = "Failed to update the instruction cache.",
        ["Signature.NoThreads"] = "No game thread could be suspended safely.",
        ["Signature.ReadFailed"] = "Failed to read 0x{0:X}.",
        ["Signature.WriteFailed"] = "Failed to write 0x{0:X}."
    };

    private static Dictionary<string, string> CreateChineseCatalog() => new(StringComparer.Ordinal)
    {
        ["App.Title"] = "CoH3 资源修改器",
        ["App.AlreadyRunningTitle"] = "修改器已在运行",
        ["App.AlreadyRunning"] = "请先关闭当前的 CoH3 资源修改器实例，再打开另一个实例。",
        ["Menu.Main"] = "主菜单",
        ["Menu.Settings"] = "_设置",
        ["Menu.Language"] = "语言",
        ["Menu.OpenSettingsFolder"] = "打开设置文件夹",
        ["Menu.OpenLogsFolder"] = "打开日志文件夹",
        ["Menu.Help"] = "_帮助",
        ["Menu.HowTo"] = "使用方法",
        ["Menu.Contributors"] = "贡献者",
        ["Menu.About"] = "关于",
        ["Header.Subtitle"] = "战役及对抗 AI 的单人/私人对局",
        ["Action.Connect"] = "连接",
        ["Action.Disconnect"] = "断开连接",
        ["Action.Retry"] = "重试",
        ["Action.Connecting"] = "正在连接...",
        ["Action.Add"] = "添加",
        ["Action.Promote"] = "全部晋升 +1",
        ["Action.Heal"] = "全部治疗",
        ["Action.ResetCooldowns"] = "重置全部冷却",
        ["Action.SaveSettings"] = "保存设置",
        ["Action.Close"] = "关闭",
        ["Status.Initializing"] = "正在初始化...",
        ["Status.WaitingData"] = "等待数据",
        ["Status.Updated"] = "更新于 {0:HH:mm:ss.fff}",
        ["Status.WaitingConnection"] = "等待连接。",
        ["Tab.Trainer"] = "修改器",
        ["Tab.Units"] = "单位",
        ["Tab.Match"] = "对局",
        ["Tab.Settings"] = "设置",
        ["Trainer.LiveDataTitle"] = "本地玩家数据 • 实时",
        ["Trainer.Instruction"] = "按已配置的按键或使用按钮。数值会累加，而不是替换。",
        ["Units.Title"] = "老练度、治疗和冷却",
        ["Units.Subtitle"] = "对本地玩家在对局中的所有小队应用操作。",
        ["Units.ConnectHint"] = "连接修改器与游戏以启用这些操作。",
        ["Units.Unsupported"] = "版本 {0} 不支持这些操作。",
        ["Units.WaitingMatch"] = "游戏已连接；正在等待对局和本地玩家。",
        ["Units.Executing"] = "正在模拟周期中应用操作...",
        ["Units.Ready"] = "就绪 • 操作将影响您的所有小队",
        ["Units.VeterancyTitle"] = "老练度",
        ["Units.VeterancyDescription"] = "将您的所有小队晋升一级，并遵守每个单位的最高等级。",
        ["Units.HealTitle"] = "治疗",
        ["Units.HealDescription"] = "将您所有小队中每个成员的生命恢复至 100%。",
        ["Units.CooldownsTitle"] = "冷却",
        ["Units.CooldownsDescription"] = "清除您所有小队技能的剩余冷却时间。",
        ["Income.DefaultShort"] = "默认收入",
        ["Income.MultiplierShort"] = "收入 {0:0.#}x",
        ["Population.ShortActive"] = "人口 {0:N0}",
        ["Population.ShortDefault"] = "默认人口",
        ["Population.ShortUnavailable"] = "人口功能不可用",
        ["Population.ShortWaiting"] = "人口 {0:N0} • 等待中",
        ["Dashboard.Title"] = "对局面板",
        ["Dashboard.Subtitle"] = "实时读取本地玩家数据。",
        ["Dashboard.ObservedTime"] = "观察时间",
        ["Dashboard.WaitingConnection"] = "等待连接游戏",
        ["Dashboard.LastSampleEmpty"] = "最后采样：—",
        ["Dashboard.LastSample"] = "最后采样：{0:HH:mm:ss}",
        ["Dashboard.VersionEmpty"] = "版本 —",
        ["Dashboard.Version"] = "版本 {0}",
        ["Dashboard.NetChange"] = "净变化：{0}/分钟",
        ["Dashboard.Income"] = "收入",
        ["Dashboard.Population"] = "人口",
        ["Dashboard.Footnote"] = "净变化统计最近 60 秒内的收入、支出和修改器操作。",
        ["Dashboard.StateDisconnected"] = "未连接",
        ["Dashboard.StateInMatch"] = "对局中",
        ["Dashboard.StateSyncing"] = "同步中",
        ["Dashboard.StateWaitingMatch"] = "等待对局",
        ["Dashboard.TelemetryActive"] = "本地玩家遥测已启用",
        ["Dashboard.TelemetryInterrupted"] = "对局数据暂时中断",
        ["Dashboard.EnterMatch"] = "游戏已连接；请进入兼容的对局",
        ["Dashboard.IncomeDefault"] = "默认 • 1x",
        ["Dashboard.IncomeActive"] = "已启用 • {0:0.#}x",
        ["Dashboard.PopActive"] = "已启用 • {0:N0}",
        ["Dashboard.PopDefault"] = "游戏默认",
        ["Dashboard.PopUnsupported"] = "此版本不可用",
        ["Dashboard.PopWaiting"] = "等待中 • {0:N0}",
        ["Settings.Title"] = "快捷键和数量",
        ["Settings.HotkeyHint"] = "每个全局快捷键可使用 F1 到 F12 中的一个按键。",
        ["Settings.IncomeMultiplier"] = "收入倍率",
        ["Settings.IncomeDescription"] = "提升检测到的人力、燃料和弹药收入。",
        ["Settings.PopulationLimit"] = "人口上限",
        ["Settings.PopulationDescription"] = "在对局中覆盖本地玩家的人口上限。",
        ["Settings.Active"] = "启用",
        ["Settings.PersistHint"] = "更改会立即应用，并为以后的会话保存。",
        ["Resource.Manpower"] = "人力",
        ["Resource.Fuel"] = "燃料",
        ["Resource.Army"] = "弹药",
        ["Resource.CommandPoints"] = "指挥点数",
        ["Resource.VictoryPoints"] = "队伍胜利点",
        ["Automation.CommandPointsAmount"] = "指挥点数数量",
        ["Automation.PopulationLimit"] = "人口上限",
        ["Tooltip.Connect"] = "查找 Company of Heroes 3",
        ["Tooltip.Disconnect"] = "断开与游戏进程的连接",
        ["Tooltip.Connecting"] = "正在连接",
        ["Event.LanguageChanged"] = "语言已更改为 {0}。",
        ["Event.SettingsFolderOpened"] = "设置文件夹已打开。",
        ["Event.LogsFolderOpened"] = "日志文件夹已打开。",
        ["Event.CannotOpenFolder"] = "无法打开文件夹：{0}",
        ["Event.SettingsSaved"] = "设置已保存。{0} {1}",
        ["Event.ErrorSaving"] = "保存时出错：{0}",
        ["Event.GameDisconnected"] = "游戏已断开连接。",
        ["Event.Connecting"] = "正在连接游戏...",
        ["Event.ConnectionFailed"] = "连接失败：{0}",
        ["Event.ReadFailed"] = "读取失败：{0}",
        ["Event.UnitActionQueued"] = "操作已发送到模拟周期...",
        ["Log.Started"] = "修改器已启动。",
        ["Log.Closed"] = "修改器已关闭。",
        ["Info.HelpSection"] = "帮助",
        ["Info.HelpHeading"] = "使用方法",
        ["Info.HelpBody"] = "1. 打开 Company of Heroes 3。\n2. 等待自动连接，或选择重试。\n3. 进入兼容的对局。\n4. 使用按钮或已配置的快捷键添加资源。\n5. 指挥点数默认使用 F9，每次增加 5 点。\n6. 在设置页调整收入倍率和人口上限。\n7. 使用单位页为您的所有小队应用老练度、治疗或冷却重置。",
        ["Info.ContributorsSection"] = "贡献者",
        ["Info.ContributorsBody"] = "CoH3 Resource Trainer 的创意发起人和项目愿景负责人。",
        ["Info.AboutSection"] = "关于",
        ["Info.AboutBody"] = "版本 {0}\n\n用于战役及对抗 AI 的单人或私人对局的本地工具。",
        ["Validation.SelectIncome"] = "请选择有效的收入倍率。",
        ["Validation.IncompleteSettings"] = "资源配置不完整。",
        ["Validation.PopulationRange"] = "人口上限必须在 {0} 到 {1} 之间。",
        ["Validation.ValidAmount"] = "请输入 {0} 的有效数量。",
        ["Validation.CommandPointsRange"] = "指挥点数数量必须在 {0} 到 {1} 之间。",
        ["Validation.ResourceRange"] = "{0} 的数量必须在 1 到 1,000,000 之间。",
        ["Validation.DistinctKeys"] = "请选择 {0} 个不同的 F 键。",
        ["Hotkey.WindowUnavailable"] = "窗口尚未初始化。",
        ["Hotkey.Invalid"] = "{0} 的按键无效：{1}",
        ["Hotkey.InUse"] = "{0} 已被其他程序使用。",
        ["Backend.Disconnected"] = "游戏未连接。",
        ["Backend.Locating"] = "正在查找 Company of Heroes 3...",
        ["Backend.NotFound"] = "未找到 Company of Heroes 3。请打开游戏后重试。",
        ["Backend.MainModuleUnavailable"] = "游戏主模块不可用。",
        ["Backend.UnknownVersion"] = "未知",
        ["Backend.Ready"] = "就绪 — 资源可用。",
        ["Backend.ConnectedWaiting"] = "游戏已连接 — 等待对局。",
        ["Backend.ConnectionFailed"] = "连接失败：{0}",
        ["Backend.ResourceNotIdentified"] = "尚未识别 {0}。请进入对局后重试。",
        ["Backend.UnsafeRead"] = "读取值超出安全范围；已取消写入。",
        ["Backend.WriteFailed"] = "写入失败：{0}",
        ["Backend.NotConfirmed"] = "游戏未确认新数值。",
        ["Backend.AtLimit"] = "{0} 已达到上限 {1:N0}。",
        ["Backend.Added"] = "{1} +{0:N0}；新数值：{2:N0}。",
        ["Backend.IncomeRestored"] = "已恢复正常收入。",
        ["Backend.IncomeActivated"] = "已启用 {0:0.#}x 收入倍率。",
        ["Backend.PopDefault"] = "已选择默认人口上限。",
        ["Backend.PopUnsupported"] = "上限已保存，但尚不兼容版本 {0}。",
        ["Backend.PopConfigured"] = "人口上限已设置为 {0:N0}。",
        ["Backend.UnitActionsUnsupported"] = "老练度、治疗和冷却尚不兼容版本 {0}。",
        ["Backend.UnitActionTimedOut"] = "对局未处理该操作。请确认对局正在运行后重试。",
        ["Backend.NoSquadsAvailable"] = "对局中没有可用的本地玩家小队。",
        ["Backend.VeterancyApplied"] = "已提升 {0:N0} 个小队的老练度。",
        ["Backend.HealApplied"] = "已恢复 {0:N0} 个小队的生命。",
        ["Backend.CooldownsApplied"] = "已重置 {0:N0} 个小队的冷却。",
        ["Backend.GameClosed"] = "游戏已关闭。准备好后请重新连接。",
        ["Backend.ModuleNotFound"] = "未找到模块 {0}。",
        ["Backend.PointerInvalid"] = "{0} 的指针链无效。",
        ["Backend.InitialValueInvalid"] = "{0} 的初始值无效。",
        ["Signature.AlreadyActive"] = "自动定位器已启用。",
        ["Signature.UnitActionInstructionsChanged"] = "单位操作调度器包含未知更改。",
        ["Signature.PlayerInstructionsChanged"] = "玩家指令包含未知更改。",
        ["Signature.CaptureAllocationFailed"] = "无法分配捕获区域。",
        ["Signature.QueueInstructionsChanged"] = "生产队列指令包含未知更改。",
        ["Signature.Recovered"] = "已从先前连接恢复自动识别。",
        ["Signature.Installed"] = "自动识别已安装；正在等待本地玩家。",
        ["Signature.ActivationFailed"] = "无法启用自动识别：{0}",
        ["Signature.PlayerDescription"] = "玩家",
        ["Signature.QueueDescription"] = "生产队列",
        ["Signature.NotFound"] = "此版本中未找到{0}自动签名。",
        ["Signature.NotUnique"] = "{0}自动签名不唯一。",
        ["Signature.CodePageFailed"] = "无法解锁代码页。",
        ["Signature.InstructionCacheFailed"] = "无法更新指令缓存。",
        ["Signature.NoThreads"] = "无法安全地挂起任何游戏线程。",
        ["Signature.ReadFailed"] = "无法读取 0x{0:X}。",
        ["Signature.WriteFailed"] = "无法写入 0x{0:X}。"
    };

    private static Dictionary<string, string> CreateSpanishCatalog() => new(StringComparer.Ordinal)
    {
        ["App.Title"] = "Entrenador de recursos CoH3",
        ["App.AlreadyRunningTitle"] = "El Trainer ya está en ejecución",
        ["App.AlreadyRunning"] = "Cierra la instancia actual de CoH3 Resource Trainer antes de abrir otra.",
        ["Menu.Main"] = "Menú principal",
        ["Menu.Settings"] = "_CONFIGURACIÓN",
        ["Menu.Language"] = "Idioma",
        ["Menu.OpenSettingsFolder"] = "Abrir carpeta de configuración",
        ["Menu.OpenLogsFolder"] = "Abrir carpeta de registros",
        ["Menu.Help"] = "_AYUDA",
        ["Menu.HowTo"] = "Cómo usar",
        ["Menu.Contributors"] = "Colaboradores",
        ["Menu.About"] = "Acerca de",
        ["Header.Subtitle"] = "Campaña y partidas individuales/privadas contra la IA",
        ["Action.Connect"] = "CONECTAR",
        ["Action.Disconnect"] = "DESCONECTAR",
        ["Action.Retry"] = "INTENTAR DE NUEVO",
        ["Action.Connecting"] = "CONECTANDO...",
        ["Action.Add"] = "AÑADIR",
        ["Action.Promote"] = "ASCENDER TODOS +1",
        ["Action.Heal"] = "CURAR TODOS",
        ["Action.ResetCooldowns"] = "REINICIAR TODOS",
        ["Action.SaveSettings"] = "GUARDAR CONFIGURACIÓN",
        ["Action.Close"] = "CERRAR",
        ["Status.Initializing"] = "Inicializando...",
        ["Status.WaitingData"] = "Esperando datos",
        ["Status.Updated"] = "Actualizado {0:HH:mm:ss.fff}",
        ["Status.WaitingConnection"] = "Esperando conexión.",
        ["Tab.Trainer"] = "TRAINER",
        ["Tab.Units"] = "UNIDADES",
        ["Tab.Match"] = "PARTIDA",
        ["Tab.Settings"] = "CONFIGURACIÓN",
        ["Trainer.LiveDataTitle"] = "DATOS DEL JUGADOR LOCAL • TIEMPO REAL",
        ["Trainer.Instruction"] = "Pulsa la tecla configurada o usa el botón. Los valores se suman, no se sustituyen.",
        ["Units.Title"] = "Veteranía, curación y cooldowns",
        ["Units.Subtitle"] = "Aplica una acción a todos los escuadrones del jugador local en la partida.",
        ["Units.ConnectHint"] = "Conecta el Trainer al juego para habilitar estas acciones.",
        ["Units.Unsupported"] = "Acciones no disponibles en la versión {0}.",
        ["Units.WaitingMatch"] = "Juego conectado; esperando una partida y al jugador local.",
        ["Units.Executing"] = "Aplicando la acción en el ciclo de simulación...",
        ["Units.Ready"] = "LISTO • las acciones afectan a todos tus escuadrones",
        ["Units.VeterancyTitle"] = "VETERANÍA",
        ["Units.VeterancyDescription"] = "Asciende todos tus escuadrones un rango, respetando el rango máximo de cada unidad.",
        ["Units.HealTitle"] = "CURACIÓN",
        ["Units.HealDescription"] = "Restaura al 100% la salud de todos los miembros de todos tus escuadrones.",
        ["Units.CooldownsTitle"] = "COOLDOWNS",
        ["Units.CooldownsDescription"] = "Elimina el tiempo de recarga restante de las habilidades de todos tus escuadrones.",
        ["Income.DefaultShort"] = "INGRESOS NORMALES",
        ["Income.MultiplierShort"] = "INGRESOS {0:0.#}x",
        ["Population.ShortActive"] = "POB {0:N0}",
        ["Population.ShortDefault"] = "POB NORMAL",
        ["Population.ShortUnavailable"] = "POB NO DISPONIBLE",
        ["Population.ShortWaiting"] = "POB {0:N0} • ESPERANDO",
        ["Dashboard.Title"] = "Panel de la partida",
        ["Dashboard.Subtitle"] = "Lectura en tiempo real del jugador local.",
        ["Dashboard.ObservedTime"] = "TIEMPO OBSERVADO",
        ["Dashboard.WaitingConnection"] = "Esperando conexión con el juego",
        ["Dashboard.LastSampleEmpty"] = "Última muestra: —",
        ["Dashboard.LastSample"] = "Última muestra: {0:HH:mm:ss}",
        ["Dashboard.VersionEmpty"] = "VERSIÓN —",
        ["Dashboard.Version"] = "VERSIÓN {0}",
        ["Dashboard.NetChange"] = "Variación neta: {0}/min",
        ["Dashboard.Income"] = "INGRESOS",
        ["Dashboard.Population"] = "POBLACIÓN",
        ["Dashboard.Footnote"] = "La variación neta incluye ingresos, gastos y acciones del trainer durante los últimos 60 segundos.",
        ["Dashboard.StateDisconnected"] = "DESCONECTADO",
        ["Dashboard.StateInMatch"] = "EN PARTIDA",
        ["Dashboard.StateSyncing"] = "SINCRONIZANDO",
        ["Dashboard.StateWaitingMatch"] = "ESPERANDO PARTIDA",
        ["Dashboard.TelemetryActive"] = "Telemetría del jugador local activa",
        ["Dashboard.TelemetryInterrupted"] = "La lectura de la partida se interrumpió temporalmente",
        ["Dashboard.EnterMatch"] = "Juego conectado; entra en una partida compatible",
        ["Dashboard.IncomeDefault"] = "NORMAL • 1x",
        ["Dashboard.IncomeActive"] = "ACTIVO • {0:0.#}x",
        ["Dashboard.PopActive"] = "ACTIVO • {0:N0}",
        ["Dashboard.PopDefault"] = "VALOR DEL JUEGO",
        ["Dashboard.PopUnsupported"] = "NO DISPONIBLE EN ESTA VERSIÓN",
        ["Dashboard.PopWaiting"] = "ESPERANDO • {0:N0}",
        ["Settings.Title"] = "Atajos y cantidades",
        ["Settings.HotkeyHint"] = "Cada atajo global acepta una tecla entre F1 y F12.",
        ["Settings.IncomeMultiplier"] = "Multiplicador de ingresos",
        ["Settings.IncomeDescription"] = "Multiplica los ingresos observados de Manpower, Fuel y Municiones.",
        ["Settings.PopulationLimit"] = "Límite de población",
        ["Settings.PopulationDescription"] = "Sustituye el límite de población del jugador local durante la partida.",
        ["Settings.Active"] = "ACTIVO",
        ["Settings.PersistHint"] = "Los cambios se aplican inmediatamente y se guardan para las próximas sesiones.",
        ["Resource.Manpower"] = "MANPOWER",
        ["Resource.Fuel"] = "FUEL",
        ["Resource.Army"] = "MUNICIONES",
        ["Resource.CommandPoints"] = "PUNTOS DE MANDO",
        ["Resource.VictoryPoints"] = "PUNTOS DE VICTORIA DEL EQUIPO",
        ["Automation.CommandPointsAmount"] = "Cantidad de puntos de mando",
        ["Automation.PopulationLimit"] = "Límite de población",
        ["Tooltip.Connect"] = "Localizar Company of Heroes 3",
        ["Tooltip.Disconnect"] = "Desconectar del proceso del juego",
        ["Tooltip.Connecting"] = "Conexión en curso",
        ["Event.LanguageChanged"] = "Idioma cambiado a {0}.",
        ["Event.SettingsFolderOpened"] = "Carpeta de configuración abierta.",
        ["Event.LogsFolderOpened"] = "Carpeta de registros abierta.",
        ["Event.CannotOpenFolder"] = "No se pudo abrir la carpeta: {0}",
        ["Event.SettingsSaved"] = "Configuración guardada. {0} {1}",
        ["Event.ErrorSaving"] = "Error al guardar: {0}",
        ["Event.GameDisconnected"] = "Juego desconectado.",
        ["Event.Connecting"] = "Conectando con el juego...",
        ["Event.ConnectionFailed"] = "Error de conexión: {0}",
        ["Event.ReadFailed"] = "Error de lectura: {0}",
        ["Event.UnitActionQueued"] = "Acción enviada al ciclo de simulación...",
        ["Log.Started"] = "Trainer iniciado.",
        ["Log.Closed"] = "Trainer cerrado.",
        ["Info.HelpSection"] = "AYUDA",
        ["Info.HelpHeading"] = "Cómo usar",
        ["Info.HelpBody"] = "1. Abre Company of Heroes 3.\n2. Espera la conexión automática o usa Intentar de nuevo.\n3. Entra en una partida compatible.\n4. Usa los botones o atajos configurados para añadir recursos.\n5. Los puntos de mando usan F9 y añaden 5 puntos de forma predeterminada.\n6. Ajusta el multiplicador de ingresos y el límite de población en Configuración.\n7. Usa la pestaña Unidades para aplicar veteranía, curación o reinicio de cooldowns a todos tus escuadrones.",
        ["Info.ContributorsSection"] = "COLABORADORES",
        ["Info.ContributorsBody"] = "Ideólogo de CoH3 Resource Trainer y responsable de la visión del proyecto.",
        ["Info.AboutSection"] = "ACERCA DE",
        ["Info.AboutBody"] = "Versión {0}\n\nHerramienta local para campaña y partidas individuales o privadas contra la IA.",
        ["Validation.SelectIncome"] = "Selecciona un multiplicador de ingresos válido.",
        ["Validation.IncompleteSettings"] = "La configuración de recursos está incompleta.",
        ["Validation.PopulationRange"] = "El límite de población debe estar entre {0} y {1}.",
        ["Validation.ValidAmount"] = "Introduce una cantidad válida para {0}.",
        ["Validation.CommandPointsRange"] = "La cantidad de puntos de mando debe estar entre {0} y {1}.",
        ["Validation.ResourceRange"] = "La cantidad de {0} debe estar entre 1 y 1.000.000.",
        ["Validation.DistinctKeys"] = "Selecciona {0} teclas F diferentes.",
        ["Hotkey.WindowUnavailable"] = "La ventana aún no está inicializada.",
        ["Hotkey.Invalid"] = "Tecla no válida para {0}: {1}",
        ["Hotkey.InUse"] = "{0} ya está en uso por otro programa.",
        ["Backend.Disconnected"] = "Juego no conectado.",
        ["Backend.Locating"] = "Localizando Company of Heroes 3...",
        ["Backend.NotFound"] = "No se encontró Company of Heroes 3. Abre el juego e inténtalo de nuevo.",
        ["Backend.MainModuleUnavailable"] = "El módulo principal del juego no está disponible.",
        ["Backend.UnknownVersion"] = "desconocida",
        ["Backend.Ready"] = "Listo — recursos disponibles.",
        ["Backend.ConnectedWaiting"] = "Juego conectado — esperando una partida.",
        ["Backend.ConnectionFailed"] = "Error de conexión: {0}",
        ["Backend.ResourceNotIdentified"] = "Aún no se identificó {0}. Entra en una partida e inténtalo de nuevo.",
        ["Backend.UnsafeRead"] = "Lectura fuera del rango seguro; escritura cancelada.",
        ["Backend.WriteFailed"] = "Error de escritura: {0}",
        ["Backend.NotConfirmed"] = "El juego no confirmó el nuevo valor.",
        ["Backend.AtLimit"] = "{0} ya está en el límite de {1:N0}.",
        ["Backend.Added"] = "+{0:N0} en {1}; nuevo valor: {2:N0}.",
        ["Backend.IncomeRestored"] = "Ingresos normales restaurados.",
        ["Backend.IncomeActivated"] = "Multiplicador de ingresos {0:0.#}x activado.",
        ["Backend.PopDefault"] = "Límite de población predeterminado seleccionado.",
        ["Backend.PopUnsupported"] = "Límite guardado, pero aún no compatible con la versión {0}.",
        ["Backend.PopConfigured"] = "Límite de población configurado en {0:N0}.",
        ["Backend.UnitActionsUnsupported"] = "Veteranía, curación y cooldowns aún no son compatibles con la versión {0}.",
        ["Backend.UnitActionTimedOut"] = "La partida no procesó la acción. Confirma que hay una partida activa e inténtalo de nuevo.",
        ["Backend.NoSquadsAvailable"] = "No hay escuadrones del jugador local disponibles en la partida.",
        ["Backend.VeterancyApplied"] = "Veteranía aumentada en {0:N0} escuadrón(es).",
        ["Backend.HealApplied"] = "Salud restaurada en {0:N0} escuadrón(es).",
        ["Backend.CooldownsApplied"] = "Cooldowns reiniciados en {0:N0} escuadrón(es).",
        ["Backend.GameClosed"] = "El juego se cerró. Vuelve a conectar cuando esté listo.",
        ["Backend.ModuleNotFound"] = "No se encontró el módulo {0}.",
        ["Backend.PointerInvalid"] = "Cadena de punteros no válida para {0}.",
        ["Backend.InitialValueInvalid"] = "Valor inicial no válido para {0}.",
        ["Signature.AlreadyActive"] = "El localizador automático ya está activo.",
        ["Signature.UnitActionInstructionsChanged"] = "El despachador de acciones de unidades contiene un cambio desconocido.",
        ["Signature.PlayerInstructionsChanged"] = "Las instrucciones del jugador contienen un cambio desconocido.",
        ["Signature.CaptureAllocationFailed"] = "No se pudo reservar el área de captura.",
        ["Signature.QueueInstructionsChanged"] = "Las instrucciones de la cola de producción contienen un cambio desconocido.",
        ["Signature.Recovered"] = "Identificación automática recuperada de una conexión anterior.",
        ["Signature.Installed"] = "Identificación automática instalada; esperando al jugador local.",
        ["Signature.ActivationFailed"] = "No se pudo activar la identificación automática: {0}",
        ["Signature.PlayerDescription"] = "del jugador",
        ["Signature.QueueDescription"] = "de la cola de producción",
        ["Signature.NotFound"] = "La firma automática {0} no se encontró en esta versión.",
        ["Signature.NotUnique"] = "La firma automática {0} no es única.",
        ["Signature.CodePageFailed"] = "No se pudo liberar la página de código.",
        ["Signature.InstructionCacheFailed"] = "No se pudo actualizar la caché de instrucciones.",
        ["Signature.NoThreads"] = "No se pudo suspender de forma segura ningún hilo del juego.",
        ["Signature.ReadFailed"] = "No se pudo leer 0x{0:X}.",
        ["Signature.WriteFailed"] = "No se pudo escribir 0x{0:X}."
    };
}
